.PHONY: pg-claude-pty
pg-claude-pty:
	cd claude-pty && go run .

.PHONY: pg-claude-msg-continuation
pg-claude-msg-continuation:
	cd claude-msg-continuation && go run .

.PHONY: pg-claude-simple-env
pg-claude-simple-env:
	cd claude-simple-env && go run .

.PHONY: pg-codex-pty
pg-codex-pty:
	cd codex-pty && go run .

.PHONY: pg-codex-msg-continuation
pg-codex-msg-continuation:
	cd codex-msg-continuation && go run .

.PHONY: pg-codex-simple-env
pg-codex-simple-env:
	cd codex-simple-env && go run .

.PHONY: pg-codex-stdio
pg-codex-stdio:
	cd codex-stdio && go run .
